export const pizzas = [
  {
    id: 1,
    name: 'Margherita',
    toppings: ['tomato sauce', 'mozzarella', 'basil'],
    price: 8.99,
  },
  {
    id: 2,
    name: 'Pepperoni',
    toppings: ['tomato sauce', 'mozzarella', 'pepperoni'],
    price: 9.99,
  },
  {
    id: 3,
    name: 'BBQ Chicken',
    toppings: ['BBQ sauce', 'chicken', 'red onions', 'cilantro'],
    price: 10.99,
  },
  {
    id: 4,
    name: 'Hawaiian',
    toppings: ['tomato sauce', 'mozzarella', 'ham', 'pineapple'],
    price: 9.49,
  },
  {
    id: 5,
    name: 'Veggie',
    toppings: [
      'tomato sauce',
      'mozzarella',
      'bell peppers',
      'olives',
      'onions',
    ],
    price: 9.99,
  },
  {
    id: 6,
    name: 'Meat Lovers',
    toppings: ['tomato sauce', 'mozzarella', 'pepperoni', 'sausage', 'bacon'],
    price: 11.99,
  },
  {
    id: 7,
    name: 'Buffalo Chicken',
    toppings: ['buffalo sauce', 'chicken', 'red onions', 'blue cheese'],
    price: 10.49,
  },
  {
    id: 8,
    name: 'Four Cheese',
    toppings: [
      'tomato sauce',
      'mozzarella',
      'cheddar',
      'gorgonzola',
      'parmesan',
    ],
    price: 9.49,
  },
  {
    id: 9,
    name: 'Taco',
    toppings: ['salsa', 'mozzarella', 'ground beef', 'lettuce', 'tomatoes'],
    price: 10.99,
  },
  {
    id: 10,
    name: 'Pesto',
    toppings: ['pesto sauce', 'mozzarella', 'chicken', 'sun-dried tomatoes'],
    price: 11.49,
  },
  {
    id: 11,
    name: 'Greek',
    toppings: ['tomato sauce', 'mozzarella', 'feta', 'olives', 'spinach'],
    price: 9.99,
  },
  {
    id: 12,
    name: 'White',
    toppings: ['alfredo sauce', 'mozzarella', 'chicken', 'mushrooms'],
    price: 10.99,
  },
  {
    id: 13,
    name: 'Supreme',
    toppings: [
      'tomato sauce',
      'mozzarella',
      'pepperoni',
      'sausage',
      'onions',
      'bell peppers',
    ],
    price: 12.49,
  },
  {
    id: 14,
    name: 'Sicilian',
    toppings: ['tomato sauce', 'mozzarella', 'anchovies', 'capers'],
    price: 9.99,
  },
  {
    id: 15,
    name: 'Mediterranean',
    toppings: ['tomato sauce', 'mozzarella', 'artichokes', 'olives', 'feta'],
    price: 10.49,
  },
  {
    id: 16,
    name: 'Philly Cheesesteak',
    toppings: ['cheese sauce', 'steak', 'onions', 'bell peppers'],
    price: 11.99,
  },
  {
    id: 17,
    name: 'Spinach Alfredo',
    toppings: ['alfredo sauce', 'mozzarella', 'spinach', 'mushrooms'],
    price: 9.99,
  },
  {
    id: 18,
    name: 'Chicken Bacon Ranch',
    toppings: ['ranch dressing', 'mozzarella', 'chicken', 'bacon'],
    price: 11.49,
  },
  {
    id: 19,
    name: 'Garlic Chicken',
    toppings: ['garlic sauce', 'mozzarella', 'chicken', 'spinach'],
    price: 10.99,
  },
  {
    id: 20,
    name: 'Sausage and Peppers',
    toppings: ['tomato sauce', 'mozzarella', 'sausage', 'bell peppers'],
    price: 9.99,
  },
  {
    id: 21,
    name: 'Mushroom and Onion',
    toppings: ['tomato sauce', 'mozzarella', 'mushrooms', 'onions'],
    price: 8.99,
  },
  {
    id: 22,
    name: 'Shrimp Scampi',
    toppings: ['garlic sauce', 'mozzarella', 'shrimp', 'parsley'],
    price: 12.99,
  },
  {
    id: 23,
    name: 'Bacon Cheeseburger',
    toppings: ['tomato sauce', 'mozzarella', 'ground beef', 'bacon', 'cheddar'],
    price: 11.49,
  },
  {
    id: 24,
    name: 'Cajun',
    toppings: [
      'tomato sauce',
      'mozzarella',
      'andouille sausage',
      'shrimp',
      'red onions',
    ],
    price: 12.49,
  },
  {
    id: 25,
    name: 'Artichoke and Feta',
    toppings: ['tomato sauce', 'mozzarella', 'artichokes', 'feta'],
    price: 9.49,
  },
  {
    id: 26,
    name: 'Chicken and Broccoli',
    toppings: ['alfredo sauce', 'mozzarella', 'chicken', 'broccoli'],
    price: 10.99,
  },
  {
    id: 27,
    name: 'Prosciutto and Arugula',
    toppings: ['tomato sauce', 'mozzarella', 'prosciutto', 'arugula'],
    price: 11.99,
  },
  {
    id: 28,
    name: 'Sun-Dried Tomato and Goat Cheese',
    toppings: [
      'tomato sauce',
      'mozzarella',
      'sun-dried tomatoes',
      'goat cheese',
    ],
    price: 10.49,
  },
  {
    id: 29,
    name: 'Quattro Stagioni',
    toppings: [
      'tomato sauce',
      'mozzarella',
      'artichokes',
      'olives',
      'mushrooms',
      'ham',
    ],
    price: 11.49,
  },
  {
    id: 30,
    name: 'Truffle Mushroom',
    toppings: ['truffle oil', 'mozzarella', 'mushrooms', 'parmesan'],
    price: 12.99,
  },
];
